apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - bind.servicefabrik.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - osb.servicefabrik.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - deployment.servicefabrik.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - kubernetes.sapcloud.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - kubedb.com
  resources:
  - Postgres
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - configmap
  verbs:
  - '*'
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - '*'
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - mutatingwebhookconfigurations
  - validatingwebhookconfigurations
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - '*'
